# Generated by Django 5.1.5 on 2025-01-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="table_numder",
            new_name="table_number",
        ),
    ]
