# Generated by Django 5.1.5 on 2025-01-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_rename_orders_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("wait", "order pending"),
                    ("done", "order ready"),
                    ("paid", "order paid"),
                ],
                default="wait",
                max_length=4,
            ),
        ),
    ]
